# Generated by Django 5.2.7 on 2026-05-16 17:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'XLSX'), ('png', 'PNG'), ('jpg', 'JPG'), ('docx', 'DOCX'), ('txt', 'TXT')], default='txt', max_length=100)),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('failed', 'FAILED'), ('pending', 'PENDING'), ('completed', 'COMPLETED')], default='pending', max_length=100)),
                ('storage_path', models.TextField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('failed', 'FAILED'), ('pending', 'PENDING'), ('completed', 'COMPLETED')], default='pending', max_length=100)),
                ('error_message', models.TextField()),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('processing_completed', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_history', to='files.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['status'], name='files_file_status_0bd07b_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_by'], name='files_file_uploade_b6f406_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created_at'], name='files_file_created_22ed95_idx'),
        ),
    ]
