# Generated by Django 5.2.7 on 2026-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processinghistory',
            old_name='processing_completed',
            new_name='processing_completed_at',
        ),
        migrations.RenameField(
            model_name='processinghistory',
            old_name='processing_started',
            new_name='processing_started_at',
        ),
        migrations.AddField(
            model_name='file',
            name='metadata',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
