# Generated by Django 5.2.7 on 2026-06-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_processing_completed_processinghistory_processing_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_hash',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
